### ISSUE TITLE
Reference Testbed

### ISSUE THREAD

**Issue by aitorce** [International-Data-Spaces-Association/metadata-broker-open-core#43] opened 2021-07-14 08:20 UTC
I am trying to make a local testbed with the following components:
- Dataspace Connector
- Omejdn DAPS
- Metadata Broker

So far we have achieved the following interoperability:
- Dataspace Connector -> Metadata Broker (through the publicly available DAPS: https://daps.aisec.fraunhofer.de)
- Dataspace Connector -> Omejdn DAPS

I am not able to have our Omejdn DAPS connect to the Metadata Broker. I have gathered a couple screenshots from the different sides to get a better look at the picture:

This is the how we are telling the Broker to connect to our DAPS as specified to us in another issue in this repo:
![DSCDAPSMB5](https://user-images.githubusercontent.com/82808687/125585884-61196ecc-d274-4f2c-be5f-3bec0031a95c.PNG)

This is the answer we get on the Dataspace Connect UI:
![DSCDAPSMB2](https://user-images.githubusercontent.com/82808687/125587104-8025ed15-aabf-4c76-85ac-686d9909c6ef.PNG)

It shows that the rejection reason is NOT_AUTHENTICATED. This NOT_AUTHENTICATED message persists whether we change line 21's value in the previous image true/false. Both of them show the same NOT_AUTHENTICATED message.

On the Metadata Broker's side, I obtain the following:
![DSCDAPSMB](https://user-images.githubusercontent.com/82808687/125587651-1b9b34d0-982b-4428-9318-472b5ac4e9b8.PNG)

"Token needs to be fetched anew from DAPS". I am not sure how to fix this, as it is unable to fetch the DAPS with the current configuration.

I also noticed a difference between the DAT our local DAPS provides and the DAT the public DAPS provides. I am not sure if the Broker expects any of the fields that our DAPS is not currently providing.

Our DAPS:
![DSCDAPSMB3](https://user-images.githubusercontent.com/82808687/125588191-00ffb8ed-3a68-414e-9b59-07d388c28e9f.PNG)

Public DAPS (default when installing the Broker)
![DSCDAPSMB4](https://user-images.githubusercontent.com/82808687/125588262-9d7467e2-b230-4b8d-96fc-844540e6d65f.PNG)

Thank you!

**Comment by sebbader** [comment] 2021-07-28 11:03
Hello Aitor! We have noted your report, @NehaThawani44 will shortly keep you updated.

**Comment by sebbader** [comment] 2021-08-23 12:28
Hello @aitorce ! I think I understand your problem. Your DAPS is not known to the Broker, therefore it doesn't trust its signiture. I assume we need to add your public key to the Broker truststore. @NehaThawani44 can you please help @aitorce to add it?

**Comment by sebbader** [comment] 2021-09-07 08:19
@NehaThawani44 and @TasneemRashid that sounds exactly like the problem we are currently facing with our own DSC instance and its truststore. Can you please give an update here as soon as the problem is solved in our testbed?

**Comment by NehaThawani44** [comment] 2021-12-06 12:13
@aitorce @gbrost @sebbader Finally after a long struggle we have finally resolved this ticket, hence I am closing it.

**Closed by NehaThawani44** 2021-12-06 12:13 UTC
